In [1]:
import brightway2 as bw
import os               # to use "operating system dependent functionality"
import numpy as np      # "the fundamental package for scientific computing with Python"
import pandas as pd     # "high-performance, easy-to-use data structures and data analysis tools" for Python
import csv
import stats_arrays
import scipy as sp
import pandas as pd
import pickle
import h5py
import time

In [2]:
bw.projects.set_current('iw_integration')

In [3]:
DB_eiv33=bw.Database('ecoinvent 3.3 cutoff')

In [4]:
act=DB_eiv33.random()

In [6]:
act.key

('ecoinvent 3.3 cutoff', '21c7a9996f3ace4693c218998512ca11')

In [4]:
act1=DB_eiv33.get('f868a8bb1c627e75df31949ecdc347b9')

In [12]:
type(act1),type(act)

(bw2data.backends.peewee.proxies.Activity,
 bw2data.backends.peewee.proxies.Activity)

In [5]:
act1.as_dict()

{'activity': 'fa51a226-12e8-4d84-8d90-2cf1ab22114d',
 'activity type': 'ordinary transforming activity',
 'authors': {'data entry': {'email': 'eth.s-u@ecoinvent.org',
   'name': 'Jürgen Sutter'},
  'data generator': {'email': 'eth.s-u@ecoinvent.org',
   'name': 'Jürgen Sutter'}},
 'classifications': [('EcoSpold01Categories', 'biomass/fuels'),
  ('ISIC rev.4 ecoinvent', '19a: Liquid and gaseous fuels from biomass')],
 'code': 'f868a8bb1c627e75df31949ecdc347b9',
 'comment': 'The multioutput-process "sugar cane, to fermentation" delivers the co-products Ethanol, 95% in H20, from sugar cane" and "electricity, bagasse, at fermentation plant".  The allocation is based on  economic criteria.\n[This dataset was already contained in the ecoinvent database version 2. It was not individually updated during the transfer to ecoinvent version 3. Life Cycle Impact Assessment results may still have changed, as they are affected by changes in the supply chain, i.e. in other datasets. This dataset was g

In [13]:
act1=DB_eiv33.random()
act2=DB_eiv33.random()
act3=DB_eiv33.random()

In [14]:
act1.key[1],act2.key[1],act3.key[1]

('e929619f245df590fee5d72dc979cdd4',
 'bdf7116059abfcc6b8b9ade1a641e578',
 'c8c815c68836adaf964daaa001a638a3')

In [10]:
act_id=act.key[1]
type(act_id)

str

In [15]:
encoded_act_id_UTF8=act_id.encode(encoding='UTF-8',errors='strict')

In [16]:
type(encoded_act_id_UTF8)

bytes

In [17]:
encoded_act_id_ascii=act_id.encode(encoding='ascii',errors='strict')
type(encoded_act_id_ascii)

bytes

In [19]:
np_act_id=np.string_(act_id)
type(np_act_id)

numpy.bytes_

In [20]:
np_act_id.dtype

dtype('S32')

In [21]:
list_act_id=[act_id,act_id,act_id]

In [23]:
list_act_id_np=np.string_(list_act_id)

In [30]:
type(list_act_id_np), type(list_act_id_np[0])

(numpy.ndarray, numpy.bytes_)

In [38]:
act_id_after_UTF8=list_act_id_np[0].decode('UTF-8')
act_id_after_ascii=list_act_id_np[0].decode('ascii')

In [39]:
act_id_after_UTF8 == act_id,act_id_after_ascii == act_id, list_act_id_np[0] == act_id

(True, True, False)

In [41]:
act_id

TypeError: format_map() takes exactly one argument (0 given)

In [7]:
act.keys()

KeysView('electricity voltage transformation from medium to low voltage' (kilowatt hour, IS, None))

In [5]:
current_path_dir=os.getcwd()
path_for_saving=current_path_dir+"\\Saved objects"
hdf5_file_name="test_saved_LCA_obj.hdf5"
hdf5_file_path=path_for_saving+"\\"+hdf5_file_name

In [6]:
hdf5_file=h5py.File(hdf5_file_path,'a')

In [10]:
hdf5_file.attrs['test']="OK"

In [13]:
[key for key in hdf5_file.attrs]

[]

In [14]:
[group for group in hdf5_file.keys()]

['per DB', 'per activity', 'per iteration', 'per iteration and activity']

In [15]:
per_DB=hdf5_file['/per DB']

In [18]:
type(len(hdf5_file))

int

In [27]:
[group for group in per_DB.keys()]

['activity_dict', 'biosphere_dict', 'product_dict']

In [30]:
biosphere_dict=hdf5_file['/per DB/biosphere_dict']

In [31]:
[group for group in biosphere_dict.keys()]

['keys', 'values']

In [32]:
biosphere_dict_keys=hdf5_file['/per DB/biosphere_dict/keys']
biosphere_dict_values=hdf5_file['/per DB/biosphere_dict/values']

In [33]:
biosphere_dict_keys.dtype,biosphere_dict_values.dtype

(dtype('int32'), dtype('int32'))

In [37]:
techno_matrix=hdf5_file['/per iteration and activity/technosphere_matrix']

In [38]:
[group for group in techno_matrix.keys()]

['data', 'indices', 'indptr']

In [39]:
techno_matrix_data=hdf5_file['/per iteration and activity/technosphere_matrix/data']
techno_matrix_indices=hdf5_file['/per iteration and activity/technosphere_matrix/indices']
techno_matrix_indptr=hdf5_file['/per iteration and activity/technosphere_matrix/indptr']

In [40]:
techno_matrix_data.dtype,techno_matrix_indices.dtype,techno_matrix_indptr.dtype

(dtype('float64'), dtype('int32'), dtype('int32'))

In [42]:
LCA_obj=bw.LCA({act:1})

In [43]:
LCA_obj.lci()

In [44]:
LCA_obj.supply_array.dtype

dtype('float64')

In [45]:
LCA_obj.bio_params.dtype

dtype([('input', '<u4'), ('output', '<u4'), ('row', '<u4'), ('col', '<u4'), ('type', 'u1'), ('uncertainty_type', 'u1'), ('amount', '<f4'), ('loc', '<f4'), ('scale', '<f4'), ('shape', '<f4'), ('minimum', '<f4'), ('maximum', '<f4'), ('negative', '?')])

In [46]:
LCA_obj.activity_dict.values

<function dict.values>

In [47]:
type(LCA_obj.bio_params)

numpy.ndarray

In [48]:
type(LCA_obj.supply_array)

numpy.ndarray

In [50]:
np.dtype('float64')

dtype('float64')

In [51]:
functional_units = [ {act.key: 1} ]

In [52]:
for act_index, fu in enumerate(functional_units):
    #Creating UUID for each activity -> should be list(act_index.keys())[0][1]
    actKey = list(fu.keys())[0][1]

In [54]:
actKey, type(actKey)

('af29a664f9a139e18d64ecdbc397e5a1', str)

In [55]:
DB_eiv33.name

'ecoinvent 3.3 cutoff'

In [56]:
LCA_obj.product_dict

{('ecoinvent 3.3 cutoff', '13ea0b258811e52ccbf76b903825e804'): 0,
 ('ecoinvent 3.3 cutoff', '31dac3ea3eddbb68323b47eafa2c4fb8'): 1,
 ('ecoinvent 3.3 cutoff', 'b47698a545fb09cff9d6b017099658ae'): 2,
 ('ecoinvent 3.3 cutoff', 'fc4d15bd907eda5c2f04ddaf46d8a4a5'): 3,
 ('ecoinvent 3.3 cutoff', '8c9f9f01eec394d61582056971d31485'): 4,
 ('ecoinvent 3.3 cutoff', 'b40e9b88403cd9233ec9f928d17ea890'): 5,
 ('ecoinvent 3.3 cutoff', '2d7ff0f07659646c160ba8f004764a0a'): 6,
 ('ecoinvent 3.3 cutoff', 'f9f01ae72330b7cb84d43b7775449acb'): 7,
 ('ecoinvent 3.3 cutoff', '4fb0448eb17f67dff778384545c6c1d0'): 8,
 ('ecoinvent 3.3 cutoff', 'e900c182f045d862158527cd8592b89c'): 9,
 ('ecoinvent 3.3 cutoff', '465059cdcabeb326e8e596c772ef0510'): 10,
 ('ecoinvent 3.3 cutoff', 'a1ada48d424d3d20c0fd311656f47e3a'): 11,
 ('ecoinvent 3.3 cutoff', 'c2cd55abf813fd23e9416607d40eb36f'): 12,
 ('ecoinvent 3.3 cutoff', 'b9882aef7cfb1cfb51c13858ccf4ec1d'): 13,
 ('ecoinvent 3.3 cutoff', '47d119e4f8c374487fe8c5e742272f15'): 14,
 ('ec

In [57]:
LCA_obj.activity_dict

{('ecoinvent 3.3 cutoff', '13ea0b258811e52ccbf76b903825e804'): 0,
 ('ecoinvent 3.3 cutoff', '31dac3ea3eddbb68323b47eafa2c4fb8'): 1,
 ('ecoinvent 3.3 cutoff', 'b47698a545fb09cff9d6b017099658ae'): 2,
 ('ecoinvent 3.3 cutoff', 'fc4d15bd907eda5c2f04ddaf46d8a4a5'): 3,
 ('ecoinvent 3.3 cutoff', '8c9f9f01eec394d61582056971d31485'): 4,
 ('ecoinvent 3.3 cutoff', 'b40e9b88403cd9233ec9f928d17ea890'): 5,
 ('ecoinvent 3.3 cutoff', '2d7ff0f07659646c160ba8f004764a0a'): 6,
 ('ecoinvent 3.3 cutoff', 'f9f01ae72330b7cb84d43b7775449acb'): 7,
 ('ecoinvent 3.3 cutoff', '4fb0448eb17f67dff778384545c6c1d0'): 8,
 ('ecoinvent 3.3 cutoff', 'e900c182f045d862158527cd8592b89c'): 9,
 ('ecoinvent 3.3 cutoff', '465059cdcabeb326e8e596c772ef0510'): 10,
 ('ecoinvent 3.3 cutoff', 'a1ada48d424d3d20c0fd311656f47e3a'): 11,
 ('ecoinvent 3.3 cutoff', 'c2cd55abf813fd23e9416607d40eb36f'): 12,
 ('ecoinvent 3.3 cutoff', 'b9882aef7cfb1cfb51c13858ccf4ec1d'): 13,
 ('ecoinvent 3.3 cutoff', '47d119e4f8c374487fe8c5e742272f15'): 14,
 ('ec

In [60]:
('ecoinvent 3.3 cutoff', '13ea0b258811e52ccbf76b903825e804')

('ecoinvent 3.3 cutoff', '13ea0b258811e52ccbf76b903825e804')

In [64]:
str_tuple=str(('ecoinvent 3.3 cutoff', '13ea0b258811e52ccbf76b903825e804'))

In [66]:
tuple_str=tuple(str_tuple)

In [44]:
type(LCA_obj.biosphere_matrix)

scipy.sparse.csr.csr_matrix

In [45]:
LCA_obj.biosphere_matrix.nnz

353369

In [46]:
len(LCA_obj.biosphere_matrix)

TypeError: sparse matrix length is ambiguous; use getnnz() or shape[0]

In [51]:
##################
# HDF5 functions #
##################

# function create a group containing all the information of a csr matrix scipy  

def csr_matrix_to_hdf5(csr,hdf5_file,group_path):
    
    # Retrieve or create groups and subgroups
    group=hdf5_file.require_group(group_path)
    
    csr_size=csr.nnz
    
    # Create datasets containing values of csr matrix
    group.create_dataset('data',data=csr.data,compression="gzip",dtype=np.float32)
    group.create_dataset('indptr',data=csr.indptr,compression="gzip")
    group.create_dataset('indices',data=csr.indices,compression="gzip")
    
    
    #data=group.create_dataset('data',(csr_size,),compression="gzip",dtype=np.float32)
    #indptr=group.create_dataset('indptr',(csr_size,),compression="gzip")
    #indices=group.create_dataset('indices',(csr_size,),compression="gzip")
    
    #data[...]=csr.data
    #indptr[...]=csr.indptr
    #indices[...]=csr.indices
    
    group.attrs['shape']=csr.shape
    
    return;


#function to create list to store in hfd5 for LCA object _dict: biosphere_dict, activity_dict, product_dict

def LCA_dict_to_hdf5(LCA_dict,hdf5_file,group_path):
    
    # Retrieve or create the groups and subgroups
    group=hdf5_file.require_group(group_path)
    
    ###### WARNING : Modify the builder because _dict items are like 
    #####('ecoinvent 3.3 cutoff', 'c533b046462b6c56a5636ca177347c48'): 35
    #### Use .decode('UTF-8') to convert keys_1_list items for bytes to str
    
    
    keys_0=[key[0] for key in LCA_dict.keys()][0]
    keys_1_list=np.string_([key[1] for key in LCA_dict.keys()])
    items_list=[item for item in LCA_dict.values()]
    
    # Create datasets containing values of csr matrix
    group.create_dataset('keys_1',data=keys_1_list,compression="gzip")
    group.create_dataset('values',data=items_list,compression="gzip")
    group.attrs['keys_0']=keys_0

    
    return;


#Function to write csr matrix, _dict from LCA objects and any numpy.ndarray

def write_LCA_obj_to_HDF5_file(LCA_obj,hdf5_file,group_path):
    
    dict_names_to_check=['biosphere_dict', 'activity_dict', 'product_dict']
    
    #If object = A or B matrix
    if type(LCA_obj)==sp.sparse.csr.csr_matrix:
        csr_matrix_to_hdf5(LCA_obj,hdf5_file,group_path)
    
    #If object = ***_dict
    elif group_path.rsplit('/', 1)[1] in dict_names_to_check:
        LCA_dict_to_hdf5(LCA_obj,hdf5_file,group_path)
        
    else:
        
        #store as float32 if type is float64 to save space
        if LCA_obj.dtype == np.dtype('float64'):
            hdf5_file.create_dataset(group_path,data=LCA_obj,compression="gzip",dtype=np.float32)
            
        else:
            hdf5_file.create_dataset(group_path,data=LCA_obj,compression="gzip")
            
    
    return;

In [2]:
current_path_dir=os.getcwd()
path_for_saving=current_path_dir+"\\Saved objects"
hdf5_file_name="test_several_objects.hdf5"
hdf5_file_path=path_for_saving+"\\"+hdf5_file_name

hdf5_file=h5py.File(hdf5_file_path,'a')
group_path='/csr_matrix'
#object_to_write=LCA_obj.biosphere_matrix

In [53]:
write_LCA_obj_to_HDF5_file(object_to_write,hdf5_file,group_path)

In [60]:
hdf5_file.close()

ValueError: Not a file id (Not a file id)

In [7]:
file_to_close=h5py.File(path_for_saving+"\\"+'LCI_Dependant_Monte_Carlo_results_worker0.hdf5')

In [59]:
file_to_close.close()

In [8]:
child_dataset_path='/techno_matrix/0/data'

In [8]:
child_dataset_path.rsplit('/', 1)[1]

'data'

In [10]:
child_dataset_path.rsplit('/', 2)[0],child_dataset_path.rsplit('/', 2)[1],child_dataset_path.rsplit('/', 2)[2]


('/techno_matrix', '0', 'data')

In [11]:
[key for key in hdf5_file]

[]

In [22]:
hdf5_file.create_dataset('/test11',shape=(8,),maxshape=(None,))
data=[1,3,4,5,6,7,976,87]

In [23]:
dataset=hdf5_file['/test10']
dataset[...]=data

In [24]:
dataset[()]

array([   1.,    3.,    4.,    5.,    6.,    7.,  976.,   87.], dtype=float32)

In [59]:
dataset[-1]=42

In [60]:
dataset[-1]

42.0

In [25]:
dataset.resize((dataset.shape[0]-1,))

In [26]:
dataset.shape

(7,)

In [63]:
dataset[-1]=54

In [27]:
dataset[()]

array([   1.,    3.,    4.,    5.,    6.,    7.,  976.], dtype=float32)

In [123]:
dataset[...]=[2,4,5,66,2,4,6,7]

In [67]:
dataset[()]

array([   1.,    3.,    4.,    5.,    6.,    7.,  976.], dtype=float32)

In [13]:
dataset.file.filename

'C:\\Users\\Laure\\Brightway - Notebooks and code\\Monte-Carlo\\Saved objects\\test_several_objects.hdf5'

In [28]:
dataset.size

7

In [68]:
hdf5_file.filename

'C:\\Users\\Laure\\Brightway - Notebooks and code\\Monte-Carlo\\Saved objects\\test_several_objects.hdf5'

In [3]:
[item for item in hdf5_file.items()]

[('group_test', <HDF5 group "/group_test" (0 members)>),
 ('test', <HDF5 dataset "test": shape (7,), type "<i4">),
 ('test10', <HDF5 dataset "test10": shape (7,), type "<f4">),
 ('test12', <HDF5 dataset "test12": shape (8,), type "<f4">),
 ('test2', <HDF5 dataset "test2": shape (7,), type "<i4">),
 ('test3', <HDF5 dataset "test3": shape (7,), type "<i4">),
 ('test4', <HDF5 dataset "test4": shape None, type "<f4">),
 ('test5', <HDF5 dataset "test5": shape (7,), type "<f4">),
 ('test6', <HDF5 dataset "test6": shape (7,), type "<f4">),
 ('test7', <HDF5 dataset "test7": shape (8,), type "<f4">),
 ('test8', <HDF5 dataset "test8": shape (4, 4), type "<f4">),
 ('test9', <HDF5 dataset "test9": shape (2, 4), type "<f4">)]

In [4]:
group=hdf5_file.create_group('group_test_1')

In [6]:
group.create_group('sub_group_test')

<HDF5 group "/group_test_1/sub_group_test" (0 members)>

In [7]:
len(group)

1

In [9]:
group.

1

In [69]:
hdf5_file_with_ext_links=h5py.File('C:\\Users\\Laure\\Brightway - Notebooks and code\\Monte-Carlo\\Saved objects\\test_several_objects_1.hdf5','a')

In [81]:
data=[1,3,4,5,6,7,976,87]
hdf5_file_with_ext_links.create_dataset('to be append 2',shape=(len(data),), maxshape=(None,))

<HDF5 dataset "to be append 2": shape (8,), type "<f4">

In [82]:
dataset_append=hdf5_file_with_ext_links['to be append 2']
dataset_append[...]=data

In [83]:
dataset_append.resize((dataset_append.shape[0]+len(data),))

In [84]:
dataset_append[()]

array([   1.,    3.,    4.,    5.,    6.,    7.,  976.,   87.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.], dtype=float32)

In [87]:
dataset_append[-len(data):]=data

In [88]:
dataset_append[()]

array([   1.,    3.,    4.,    5.,    6.,    7.,  976.,   87.,    1.,
          3.,    4.,    5.,    6.,    7.,  976.,   87.], dtype=float32)

In [89]:
dataset_append[-1:] = 6

In [90]:
dataset_append[()]

array([   1.,    3.,    4.,    5.,    6.,    7.,  976.,   87.,    1.,
          3.,    4.,    5.,    6.,    7.,  976.,    6.], dtype=float32)

In [91]:
value=8

In [92]:
type(value)

int

In [95]:
len(np.asarray(value))

TypeError: len() of unsized object

In [97]:
value_to_array=np.atleast_1d(value)

In [98]:
type(value_to_array),len(value_to_array)

(numpy.ndarray, 1)

In [6]:
hdf5_file.create_dataset('/test12',shape=(8,),maxshape=(None,))
data=[1,3,4,5,6,7,976,87]

In [7]:
dataset=hdf5_file['/test12']
dataset[...]=data

In [9]:
dataset[...]=dataset[()]+data

In [10]:
dataset[()]

array([    2.,     6.,     8.,    10.,    12.,    14.,  1952.,   174.], dtype=float32)

In [12]:
min(dataset)

2.0

In [14]:
np.percentile(dataset,50)

11.0

In [6]:
ic_name=('CML 2001', 'climate change', 'GWP 100a')
method=bw.Method(ic_name)

In [44]:
bw.methods

Methods dictionary with 1032 objects, including:
	('CML 2001', 'acidification potential', 'average European')
	('CML 2001', 'acidification potential', 'generic')
	('CML 2001', 'climate change', 'GWP 100a')
	('CML 2001', 'climate change', 'GWP 20a')
	('CML 2001', 'climate change', 'GWP 500a')
	('CML 2001', 'climate change', 'lower limit of net GWP')
	('CML 2001', 'climate change', 'upper limit of net GWP')
	('CML 2001', 'eutrophication potential', 'average European')
	('CML 2001', 'eutrophication potential', 'generic')
	('CML 2001', 'freshwater aquatic ecotoxicity', 'FAETP 100a')
Use `list(this object)` to get the complete list.

In [7]:
act=DB_eiv33.get('f868a8bb1c627e75df31949ecdc347b9')

In [8]:
LCA_obj=bw.LCA({act:1},ic_name)

In [9]:
LCA_obj.lci()

In [14]:
LCA_obj.bio_params

array([ (   1,  5016,    0,    57, 2, 2,   6.14740129e-05,  -9.6968956 ,  0.28495613,  nan,  nan,  nan, False),
       (   1,  5029,    0,    70, 2, 2,   4.99028010e-06, -12.2080183 ,  0.24617067,  nan,  nan,  nan, False),
       (   1,  5100,    0,   141, 2, 2,   2.76879007e-07, -15.09968567,  0.05744563,  nan,  nan,  nan, False),
       ...,
       (4026, 18773, 1958, 13814, 2, 2,   1.80029136e-04,  -8.6223917 ,  0.57445627,  nan,  nan,  nan, False),
       (4029, 14719, 1959,  9760, 2, 2,   3.42019997e-03,  -5.67805624,  0.4669047 ,  nan,  nan,  nan, False),
       (4029, 16287, 1959, 11328, 2, 2,   3.42019997e-03,  -5.67805624,  0.4669047 ,  nan,  nan,  nan, False)],
      dtype=[('input', '<u4'), ('output', '<u4'), ('row', '<u4'), ('col', '<u4'), ('type', 'u1'), ('uncertainty_type', 'u1'), ('amount', '<f4'), ('loc', '<f4'), ('scale', '<f4'), ('shape', '<f4'), ('minimum', '<f4'), ('maximum', '<f4'), ('negative', '?')])

In [13]:
LCA_obj.bio_params['row']

array([   0,    0,    0, ..., 1958, 1959, 1959], dtype=uint32)

In [15]:
LCA_obj.bio_params['negative']

array([False, False, False, ..., False, False, False], dtype=bool)

In [16]:
len(LCA_obj.bio_params)

353369

In [19]:
LCA_obj.bio_params[0]['uncertainty_type']

2

In [36]:
selection_bio_params=np.array([bio_param for bio_param in LCA_obj.bio_params if bio_param['col']==9760])

In [37]:
selection_bio_params['col']

array([9760, 9760, 9760, 9760, 9760, 9760, 9760, 9760, 9760, 9760, 9760,
       9760, 9760], dtype=uint32)

In [33]:
type(LCA_obj.bio_params)

numpy.ndarray

In [46]:
act_input_params=np.array([bio_param for bio_param in LCA_obj.bio_params if bio_param['col']==100000000])

In [48]:
act_input_params
array_empty=np.array([])

In [51]:
act_input_params[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [56]:
LCA_obj.bio_params[0]==LCA_obj.bio_params[1]

False

In [126]:
LCA_obj.bio_params[0:9]

array([ (1, 5016, 0,  57, 2, 2,   6.14740129e-05,  -9.69689560e+00,  0.28495613,  nan,  nan,  nan, False),
       (1, 5029, 0,  70, 2, 2,   4.99028010e-06,  -1.22080183e+01,  0.24617067,  nan,  nan,  nan, False),
       (1, 5100, 0, 141, 2, 1,   2.76879007e-07,  -1.50996857e+01,  0.05744563,  nan,  nan,  nan, False),
       (1, 5128, 0, 169, 2, 2,   3.74944989e-06,  -1.24939013e+01,  0.06244998,  nan,  nan,  nan, False),
       (1, 5211, 0, 252, 2, 2,   3.03260003e-05,  -1.04035053e+01,  0.45825756,  nan,  nan,  nan, False),
       (1, 5259, 0, 300, 2, 0,   3.59246565e-04,   3.59246565e-04,         nan,  nan,  nan,  nan, False),
       (1, 5262, 0, 303, 2, 2,   3.50496009e-07,  -1.48639164e+01,  0.05744563,  nan,  nan,  nan, False),
       (1, 5292, 0, 333, 2, 2,   4.60000010e-04,  -7.68428421e+00,  0.40496913,  nan,  nan,  nan, False),
       (1, 5406, 0, 447, 2, 2,   6.24858671e-07,  -1.42857399e+01,  0.29866368,  nan,  nan,  nan, False)],
      dtype=[('input', '<u4'), ('output', '<

In [128]:
corr_bio_params=LCA_obj.bio_params[0:9]
input_row_col_to_remove=(0,141)
input_condition=np.where((corr_bio_params['row'] == input_row_col_to_remove[0]) * (corr_bio_params['col'] == input_row_col_to_remove[1]))
corr_bio_params[input_condition[0].tolist()[0]]['uncertainty_type']=1
corr_bio_params

array([ (1, 5016, 0,  57, 2, 2,   6.14740129e-05,  -9.69689560e+00,  0.28495613,  nan,  nan,  nan, False),
       (1, 5029, 0,  70, 2, 2,   4.99028010e-06,  -1.22080183e+01,  0.24617067,  nan,  nan,  nan, False),
       (1, 5100, 0, 141, 2, 1,   2.76879007e-07,  -1.50996857e+01,  0.05744563,  nan,  nan,  nan, False),
       (1, 5128, 0, 169, 2, 2,   3.74944989e-06,  -1.24939013e+01,  0.06244998,  nan,  nan,  nan, False),
       (1, 5211, 0, 252, 2, 2,   3.03260003e-05,  -1.04035053e+01,  0.45825756,  nan,  nan,  nan, False),
       (1, 5259, 0, 300, 2, 0,   3.59246565e-04,   3.59246565e-04,         nan,  nan,  nan,  nan, False),
       (1, 5262, 0, 303, 2, 2,   3.50496009e-07,  -1.48639164e+01,  0.05744563,  nan,  nan,  nan, False),
       (1, 5292, 0, 333, 2, 2,   4.60000010e-04,  -7.68428421e+00,  0.40496913,  nan,  nan,  nan, False),
       (1, 5406, 0, 447, 2, 2,   6.24858671e-07,  -1.42857399e+01,  0.29866368,  nan,  nan,  nan, False)],
      dtype=[('input', '<u4'), ('output', '<

In [125]:
corr_bio_params[condition[0].tolist()[0]]['uncertainty_type']=1
corr_bio_params

array([ (1, 5016, 0,  57, 2, 2,   6.14740129e-05,  -9.69689560e+00,  0.28495613,  nan,  nan,  nan, False),
       (1, 5029, 0,  70, 2, 2,   4.99028010e-06,  -1.22080183e+01,  0.24617067,  nan,  nan,  nan, False),
       (1, 5100, 0, 141, 2, 1,   2.76879007e-07,  -1.50996857e+01,  0.05744563,  nan,  nan,  nan, False),
       (1, 5128, 0, 169, 2, 2,   3.74944989e-06,  -1.24939013e+01,  0.06244998,  nan,  nan,  nan, False),
       (1, 5211, 0, 252, 2, 2,   3.03260003e-05,  -1.04035053e+01,  0.45825756,  nan,  nan,  nan, False),
       (1, 5259, 0, 300, 2, 0,   3.59246565e-04,   3.59246565e-04,         nan,  nan,  nan,  nan, False),
       (1, 5262, 0, 303, 2, 2,   3.50496009e-07,  -1.48639164e+01,  0.05744563,  nan,  nan,  nan, False),
       (1, 5292, 0, 333, 2, 2,   4.60000010e-04,  -7.68428421e+00,  0.40496913,  nan,  nan,  nan, False),
       (1, 5406, 0, 447, 2, 2,   6.24858671e-07,  -1.42857399e+01,  0.29866368,  nan,  nan,  nan, False)],
      dtype=[('input', '<u4'), ('output', '<

In [112]:
corr_bio_params[condition]

array([ (1, 5100, 0, 141, 2, 2,   2.76879007e-07, -15.09968567,  0.05744563,  nan,  nan,  nan, False)],
      dtype=[('input', '<u4'), ('output', '<u4'), ('row', '<u4'), ('col', '<u4'), ('type', 'u1'), ('uncertainty_type', 'u1'), ('amount', '<f4'), ('loc', '<f4'), ('scale', '<f4'), ('shape', '<f4'), ('minimum', '<f4'), ('maximum', '<f4'), ('negative', '?')])

In [96]:
corr_bio_params[np.where((corr_bio_params['row'] == input_row_col_to_remove[0]) & (corr_bio_params['col'] == input_row_col_to_remove[1]))]['uncertainty_type']

array([2], dtype=uint8)

In [124]:
condition[0].tolist()[0]

2

In [129]:
for i in []:
    print('ok')

In [40]:

LCA_obj.lcia()

In [41]:
inventory=LCA_obj.inventory
characterization_matrix=LCA_obj.characterization_matrix
supply_array=LCA_obj.supply_array
biosphere_matrix=LCA_obj.biosphere_matrix
activity_dict=LCA_obj.activity_dict

In [80]:
supply_array.size

13831

In [78]:
biosphere_matrix

<1960x13831 sparse matrix of type '<class 'numpy.float64'>'
	with 353369 stored elements in Compressed Sparse Row format>

In [81]:
inventory_array=biosphere_matrix * supply_array

In [93]:
inventory_array.shape,type(inventory_array)

((1960,), numpy.ndarray)

In [84]:
characterization_matrix_array=np.array(characterization_matrix.sum(1))

In [94]:
characterization_matrix_array.shape,type(characterization_matrix_array)

((1960, 1), numpy.ndarray)

In [86]:
impact_score_scalar=characterization_matrix_array * inventory_array

In [88]:
impact_score_scalar.size

3841600

In [89]:
1960*1960

3841600

In [107]:
cf_reshaped=np.reshape(characterization_matrix_array,characterization_matrix_array.shape[0])

In [108]:
cf_reshaped.shape

(1960,)

In [103]:
impact_score_scalar=characterization_matrix_array * inventory_array

In [104]:
impact_score_scalar

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.80866612e-05,   2.71894351e-08,   6.47097096e-07, ...,
          2.84251145e-08,   1.63892345e-02,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00]])

In [109]:
impact_score_scalar=np.dot(cf_reshaped,inventory_array)

In [110]:
impact_score_scalar

10.899990544052148

In [42]:
count = len(activity_dict)
inventory_matrix = biosphere_matrix * sp.sparse.spdiags([supply_array], [0], count, count)

In [43]:
inventory_matrix

<1960x13831 sparse matrix of type '<class 'numpy.float64'>'
	with 248191 stored elements in Compressed Sparse Row format>

In [116]:
inventory_matrix != inventory

<1960x13831 sparse matrix of type '<class 'numpy.bool_'>'
	with 0 stored elements in Compressed Sparse Row format>

In [117]:
impact_score_matrix=characterization_matrix * inventory_matrix

In [118]:
impact_score_matrix

<1960x13831 sparse matrix of type '<class 'numpy.float64'>'
	with 13227 stored elements in Compressed Sparse Row format>

In [119]:
LCA_obj.score

10.899990544052148

In [120]:
impact_score_matrix.sum()

10.899990544052148

In [126]:
LCA_obj.supply_array.shape

(13831,)

In [59]:
LCA_obj1=bw.LCA({act:1},ic_name)

In [60]:
LCA_obj1.lci()

In [48]:
LCA_obj.lci()

In [50]:
LCA_obj._biosphere_dict

{1: 0,
 2: 1,
 6: 2,
 7: 3,
 11: 4,
 12: 5,
 14: 6,
 15: 7,
 16: 8,
 19: 9,
 22: 10,
 23: 11,
 24: 12,
 25: 13,
 33: 14,
 34: 15,
 40: 16,
 41: 17,
 42: 18,
 44: 19,
 45: 20,
 46: 21,
 47: 22,
 48: 23,
 51: 24,
 52: 25,
 53: 26,
 54: 27,
 55: 28,
 57: 29,
 58: 30,
 59: 31,
 60: 32,
 63: 33,
 64: 34,
 67: 35,
 69: 36,
 70: 37,
 73: 38,
 77: 39,
 78: 40,
 79: 41,
 80: 42,
 81: 43,
 82: 44,
 83: 45,
 87: 46,
 88: 47,
 93: 48,
 94: 49,
 97: 50,
 101: 51,
 102: 52,
 103: 53,
 105: 54,
 106: 55,
 108: 56,
 110: 57,
 111: 58,
 114: 59,
 115: 60,
 124: 61,
 127: 62,
 128: 63,
 130: 64,
 131: 65,
 134: 66,
 135: 67,
 137: 68,
 138: 69,
 139: 70,
 143: 71,
 145: 72,
 146: 73,
 148: 74,
 150: 75,
 151: 76,
 152: 77,
 153: 78,
 154: 79,
 155: 80,
 156: 81,
 157: 82,
 163: 83,
 165: 84,
 171: 85,
 175: 86,
 177: 87,
 178: 88,
 179: 89,
 180: 90,
 184: 91,
 186: 92,
 187: 93,
 191: 94,
 192: 95,
 193: 96,
 195: 97,
 196: 98,
 199: 99,
 200: 100,
 201: 101,
 206: 102,
 207: 103,
 209: 104,
 210: 105,

In [51]:
LCA_obj.biosphere_dict

{('biosphere3', 'a861cfae-a310-4e9d-b9eb-5d555c9a684c'): 0,
 ('biosphere3', '4010918f-7fd0-4925-8fbb-8fd7a44a806c'): 1,
 ('biosphere3', 'b465eb7f-dfe9-4057-ad17-c451d58fd753'): 2,
 ('biosphere3', '2460f868-54a9-404c-bec8-c809a44ae72c'): 3,
 ('biosphere3', 'dfe1da1e-7756-4f7e-a393-6d5e2342a962'): 4,
 ('biosphere3', 'ef6dd09f-bddc-49b4-a207-dbaec2f07bb5'): 5,
 ('biosphere3', '381a22c9-3722-4378-810d-86958f7b6d32'): 6,
 ('biosphere3', 'a8fea8cf-9b09-49fc-aa58-5a732494a2a0'): 7,
 ('biosphere3', '50eebfd4-1b99-45d6-a149-68a6d4568cb4'): 8,
 ('biosphere3', '3c054a6e-2f9c-4e5e-9231-c61bc85a250a'): 9,
 ('biosphere3', '00012c0a-9bff-4787-a7eb-56c3d2f43692'): 10,
 ('biosphere3', '0eba8639-12c1-40ce-b1b6-e3394ec94dc0'): 11,
 ('biosphere3', '127ff74d-018b-43b9-8a4e-fb5577d5ee5a'): 12,
 ('biosphere3', '0ed1b1a1-e56d-4860-bac7-d76a39bde930'): 13,
 ('biosphere3', '3184c902-c587-4fd7-bd89-769d3cf30072'): 14,
 ('biosphere3', '062a6faf-b1a5-4a6a-aa02-47ae3ec566a8'): 15,
 ('biosphere3', '31b4eea9-640e-405

In [52]:
len(LCA_obj.biosphere_dict)

1960

In [55]:
biosphere_db=bw.Database('biosphere3')

In [57]:
len(biosphere_db)

4029

In [61]:
LCA_obj1.biosphere_dict == LCA_obj.biosphere_dict

True

In [62]:
act_check1=DB_eiv33.get('bdf7116059abfcc6b8b9ade1a641e578')

In [64]:
LCA_check1=bw.LCA({act_check1:1},ic_name)

In [65]:
LCA_check1.lci()
LCA_check1.lcia()

In [66]:
LCA_check1.score

3.3223288402709876

In [99]:
child_dataset_path='/fsg/jsgfhjd/0/hsfgdsh'

In [101]:
child_dataset_path.rsplit('/', 2)[1]

'0'

In [102]:
child_dataset_path.rsplit('/', 2)[2]

'hsfgdsh'

# test on hdf5 files

In [5]:
#current_path_dir=os.getcwd()
#path_for_saving=current_path_dir+"\\Saved objects"
#hdf5_file_name="test_several_objects.hdf5"
#hdf5_file_path=path_for_saving+"\\"+hdf5_file_name

hdf5_file=h5py.File('D:\Dossiers professionnels\Logiciels\Brightway 2\Test Dependant LCI Monte Carlo\LCI_Dependant_Monte_Carlo_results_worker0.hdf5','a')
#group_path='/csr_matrix'

In [7]:
s_act1_iter1=hdf5_file['/supply_array/bdf7116059abfcc6b8b9ade1a641e578/1']
s_act1_iter10=hdf5_file['/supply_array/bdf7116059abfcc6b8b9ade1a641e578/10']

In [8]:
s_act1_iter1 == s_act1_iter10

False

In [12]:
ratio_1_10=[iter1/iter10 for (iter1,iter10) in zip(s_act1_iter1,s_act1_iter10)]

C:\Users\Laure\Anaconda3\envs\Brighway2\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in float_scalars
  """Entry point for launching an IPython kernel.


In [13]:
s_act1_iter1=hdf5_file['/supply_array/bdf7116059abfcc6b8b9ade1a641e578/1']
s_act1_iter5=hdf5_file['/supply_array/bdf7116059abfcc6b8b9ade1a641e578/5']
ratio_1_5=[iter1/iter5 for (iter1,iter5) in zip(s_act1_iter1,s_act1_iter5)]

C:\Users\Laure\Anaconda3\envs\Brighway2\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in float_scalars
  This is separate from the ipykernel package so we can avoid doing imports until


In [15]:
ratio_1_5 == ratio_1_10

False

In [5]:
dict_test={}
dict_test['gdg']=['hghjg']
dict_test['gdg']['hgfh']=8657.76

TypeError: list indices must be integers or slices, not str

In [6]:
act=dict_test['gdg']['hgfh']

TypeError: list indices must be integers or slices, not str

In [52]:
x1=[(5,6),(789,90)]
x2=[(5,6),(3,90)]

In [53]:
set_x12=set(x1+x2)

In [55]:
(5,6) in set_x12

True

In [97]:
#######Functions to calculate correlated LCI######

def calculate_ratio_corr_lognormal(gmean_Xi,gmean_Yj,gsigma_Xi,gsigma_Yj):
    
    #We assume that Xi and Yj are perfeclty correlated
    gsigma_XiYj=gsigma_Xi*gsigma_Yj
    
    gmean_Aij=gmean_Xi-gmean_Yj
    gsigma_Aij=np.sqrt((gsigma_Xi**2)+(gsigma_Yj**2)-(2*gsigma_XiYj))
    
    if np.isnan(gsigma_Aij):
        gsigma_Aij=0.00000000000000001
    
    return {'loc':gmean_Aij,'scale':gsigma_Aij};


#Only once for the DB
def calculate_ratio_corr_lognormal_for_DB(corr_ef_code_input,
                                          corr_ef_code_output,
                                          corr_twin_ef_input_output,
                                          biosphere_dict,
                                          bio_params,biosphere_names):
    
    corr_bio_params=bio_params
    ratio_rv_dict_per_activity={}
    inv_biosphere_dict={indice: ef for ef, indice in biosphere_dict.items()}
    
    set_efs=set([key[1] for key in biosphere_dict.keys()])
    
    #Isolate bio_params of interest: from corr_ef_code and with lognormal uncertainty
    corr_input_indices=[biosphere_dict[('biosphere3',code)] for code in corr_ef_code_input if code in set_efs]
    corr_output_indices=[biosphere_dict[('biosphere3',code)] for code in corr_ef_code_output if code in set_efs]
    corr_twin_indices=[(biosphere_dict[('biosphere3',code[0])],biosphere_dict[('biosphere3',code[1])]) for code in corr_twin_ef_input_output if (code[0] in set_efs and code[1] in set_efs)]
    corr_input_twin_indices=[indice[0] for indice in corr_twin_indices]
    corr_output_twin_indices=[indice[1] for indice in corr_twin_indices]
    corr_twin_indices_dict={indice[0]:indice[1] for indice in corr_twin_indices}
    
    #print(corr_twin_indices_dict)
    
    set_input=set(corr_input_indices)
    set_output=set(corr_output_indices)
    set_input_output=set(corr_input_indices+corr_output_indices)
    
    set_twin=set(corr_twin_indices)
    set_input_twin=set(corr_input_twin_indices)
    set_output_twin=set(corr_output_twin_indices)
    set_input_output_twin=set(corr_input_twin_indices+corr_output_twin_indices)
    
    
    selected_bio_params=np.array([bio_param for bio_param in bio_params if (bio_param['row'] in set_input_output and bio_param['uncertainty_type']==2)])
    
    #Per activity
    set_col_indices=list(set(selected_bio_params['col']))
    
    for col in set_col_indices:
        
        act_bio_params=np.array([bio_param for bio_param in selected_bio_params if bio_param['col']==col])
        
        #Test if {input}=0 or {output}=0 --> exclude the activity from the list
        act_input_params=np.array([bio_param for bio_param in act_bio_params if bio_param['row'] in set_input])
        act_output_params=np.array([bio_param for bio_param in act_bio_params if bio_param['row'] in set_output])
        
        try:
            act_input_params[0]
        except IndexError:
            continue
            
        try:
            act_output_params[0]
        except IndexError:
            continue
            
        
        #Test if input=output for twin ef --> remove uncertainty from the bio_params
        act_input_twin_params=np.array([bio_param for bio_param in act_input_params if (bio_param['row'] in set_input_twin and bio_param['row'] in set_input_output_twin)])
        act_output_twin_params=np.array([bio_param for bio_param in act_output_params if (bio_param['row'] in set_output_twin and bio_param['row'] in set_input_output_twin)])
        
        try:
            act_input_twin_params[0]
            
            for twin_input_row in act_input_twin_params['row']:
                twin_output_row=corr_twin_indices_dict[twin_input_row]
                
                output_twin_params=np.array([bio_param for bio_param in act_output_twin_params if bio_param['row']==twin_output_row])
                
                try:
                    output_twin_param=output_twin_params[0]
                    input_twin_param=np.array([bio_param for bio_param in act_input_twin_params if bio_param['row']==twin_input_row])[0]
                    
                    input_row_col_to_remove=(input_twin_param['row'],input_twin_param['col'])
                    output_row_col_to_remove=(output_twin_param['row'],output_twin_param['col'])
                                        
                    if input_twin_param['scale']==output_twin_param['scale']:                        
                        input_condition=np.where((corr_bio_params['row'] == input_row_col_to_remove[0]) * (corr_bio_params['col'] == input_row_col_to_remove[1]))
                        corr_bio_params[input_condition[0].tolist()[0]]['uncertainty_type']=1
                        act_input_params=[bio_param for bio_param in act_input_params if (bio_param['row'] != input_row_col_to_remove[0] and bio_param['col'] != input_row_col_to_remove[1])]
                        
                        output_condition=np.where((corr_bio_params['row'] == output_row_col_to_remove[0]) * (corr_bio_params['col'] == output_row_col_to_remove[1]))
                        corr_bio_params[output_condition[0].tolist()[0]]['uncertainty_type']=1
                        act_output_params=[bio_param for bio_param in act_output_params if (bio_param['row'] != output_row_col_to_remove[0] and bio_param['col'] != output_row_col_to_remove[1])]
                        
                        print(col,biosphere_names[inv_biosphere_dict[input_row_col_to_remove[0]]],biosphere_names[inv_biosphere_dict[output_row_col_to_remove[0]]])
                        
                except IndexError:
                    pass
            
        except IndexError:
            pass
            
        
        #Calculate Aij ratio lognormal rv and Store Aij and associate it with Yj only
        for input_param in act_input_params:
            for output_param in act_output_params:
                gmean_Xi=input_param['loc']
                gmean_Yj=output_param['loc']
                gsigma_Xi=input_param['scale']
                gsigma_Yj=output_param['scale']
                params_Aij_dict=calculate_ratio_corr_lognormal(gmean_Xi,gmean_Yj,gsigma_Xi,gsigma_Yj)
                ratio_rv_dict_per_activity[col]={output_param['row']:{input_param['row']:params_Aij_dict}}
                
                #print(type(params_Aij_dict['scale']))
                
                if np.isnan(params_Aij_dict['scale']):
                    print(col,biosphere_names[inv_biosphere_dict[input_param['row']]],biosphere_names[inv_biosphere_dict[output_param['row']]])
                                                 
    return (ratio_rv_dict_per_activity,corr_bio_params);

In [4]:
act=DB_eiv33.get('f868a8bb1c627e75df31949ecdc347b9')
LCA_obj=bw.LCA({act:1})
LCA_obj.lci()

In [13]:
len(LCA_obj.biosphere_dict)

1960

In [14]:
biosphere3=bw.Database('biosphere3')

In [62]:
land_transfo_efs=[ef for ef in biosphere3 if 'Transformation, ' in str(ef)]
land_transfo_input={ef['name'].rsplit('Transformation, from ',1)[1]:ef for ef in land_transfo_efs if ', from' in str(ef)}
land_transfo_output={ef['name'].rsplit('Transformation, to ',1)[1]:ef for ef in land_transfo_efs if ', to' in str(ef)}
corr_twin_land_transfo=[(land_transfo_input[end_name]['code'],land_transfo_output[end_name]['code']) for end_name in land_transfo_input.keys()]
land_transfo_code_input=[ef['code'] for ef in land_transfo_input.values()]
land_transfo_code_output=[ef['code'] for ef in land_transfo_output.values()]


len(land_transfo_efs), len (land_transfo_input), len(land_transfo_output),len(corr_twin_land_transfo)

(120, 60, 60, 60)

In [99]:
corr_ef_code_input=land_transfo_code_input
corr_ef_code_output=land_transfo_code_output
corr_twin_ef_input_output=corr_twin_land_transfo
biosphere_dict=LCA_obj.biosphere_dict
bio_params=LCA_obj.bio_params
biosphere_names={('biosphere3',ef['code']):ef['name'] for ef in biosphere3}

(ratio_rv_dict_per_activity,correlated_bio_params)=calculate_ratio_corr_lognormal_for_DB(corr_ef_code_input, 
                              corr_ef_code_output, 
                              corr_twin_ef_input_output, 
                              biosphere_dict, 
                              bio_params,biosphere_names)

1 Transformation, from permanent crop, irrigated Transformation, to permanent crop, irrigated
8201 Transformation, from unspecified Transformation, to unspecified
8201 Transformation, from industrial area Transformation, to industrial area
33 Transformation, from arable land, unspecified use Transformation, to arable land, unspecified use
36 Transformation, from annual crop, non-irrigated, intensive Transformation, to annual crop, non-irrigated, intensive
8248 Transformation, from annual crop, non-irrigated, intensive Transformation, to annual crop, non-irrigated, intensive
106 Transformation, from arable land, unspecified use Transformation, to arable land, unspecified use
8302 Transformation, from pasture, man made Transformation, to pasture, man made
8308 Transformation, from unspecified Transformation, to unspecified
8308 Transformation, from industrial area Transformation, to industrial area
8321 Transformation, from industrial area Transformation, to industrial area
8331 Transfor

971 Transformation, from unspecified Transformation, to unspecified
971 Transformation, from industrial area Transformation, to industrial area
9178 Transformation, from annual crop, non-irrigated Transformation, to annual crop, non-irrigated
9196 Transformation, from unspecified Transformation, to unspecified
9196 Transformation, from mineral extraction site Transformation, to mineral extraction site
1012 Transformation, from annual crop, non-irrigated, extensive Transformation, to annual crop, non-irrigated, extensive
1021 Transformation, from permanent crop, irrigated Transformation, to permanent crop, irrigated
9268 Transformation, from permanent crop, irrigated Transformation, to permanent crop, irrigated
9302 Transformation, from permanent crop Transformation, to permanent crop
9313 Transformation, from arable land, unspecified use Transformation, to arable land, unspecified use
1124 Transformation, from permanent crop, irrigated, intensive Transformation, to permanent crop, irri

9968 Transformation, from annual crop, non-irrigated, intensive Transformation, to annual crop, non-irrigated, intensive
9994 Transformation, from unspecified Transformation, to unspecified
9994 Transformation, from industrial area Transformation, to industrial area
1810 Transformation, from unspecified Transformation, to unspecified
1810 Transformation, from mineral extraction site Transformation, to mineral extraction site
10005 Transformation, from permanent crop, irrigated Transformation, to permanent crop, irrigated
10021 Transformation, from permanent crop, irrigated Transformation, to permanent crop, irrigated
10029 Transformation, from forest, extensive Transformation, to forest, extensive
10029 Transformation, from traffic area, rail/road embankment Transformation, to traffic area, rail/road embankment
1919 Transformation, from pasture, man made, intensive Transformation, to pasture, man made, intensive
1919 Transformation, from pasture, man made, extensive Transformation, to 

2640 Transformation, from annual crop Transformation, to annual crop
10852 Transformation, from arable land, unspecified use Transformation, to arable land, unspecified use
10880 Transformation, from arable land, unspecified use Transformation, to arable land, unspecified use
2689 Transformation, from annual crop, non-irrigated, extensive Transformation, to annual crop, non-irrigated, extensive
10887 Transformation, from arable land, unspecified use Transformation, to arable land, unspecified use
2697 Transformation, from annual crop, non-irrigated Transformation, to annual crop, non-irrigated
10903 Transformation, from annual crop, non-irrigated, extensive Transformation, to annual crop, non-irrigated, extensive
10924 Transformation, from annual crop, non-irrigated, intensive Transformation, to annual crop, non-irrigated, intensive
2744 Transformation, from unspecified Transformation, to unspecified
2744 Transformation, from mineral extraction site Transformation, to mineral extractio

3679 Transformation, from forest, intensive Transformation, to forest, intensive
3681 Transformation, from annual crop, non-irrigated, extensive Transformation, to annual crop, non-irrigated, extensive
11880 Transformation, from annual crop Transformation, to annual crop
11901 Transformation, from annual crop, non-irrigated, extensive Transformation, to annual crop, non-irrigated, extensive
3737 Transformation, from annual crop Transformation, to annual crop
3750 Transformation, from dump site, slag compartment Transformation, to dump site, slag compartment
3750 Transformation, from shrub land, sclerophyllous Transformation, to shrub land, sclerophyllous
11945 Transformation, from arable land, unspecified use Transformation, to arable land, unspecified use
3769 Transformation, from annual crop, non-irrigated, intensive Transformation, to annual crop, non-irrigated, intensive
3769 Transformation, from annual crop Transformation, to annual crop
11964 Transformation, from dump site, resid

12777 Transformation, from annual crop, non-irrigated, intensive Transformation, to annual crop, non-irrigated, intensive
4585 Transformation, from unspecified Transformation, to unspecified
4585 Transformation, from industrial area Transformation, to industrial area
4596 Transformation, from traffic area, rail/road embankment Transformation, to traffic area, rail/road embankment
4596 Transformation, from forest, intensive Transformation, to forest, intensive
4623 Transformation, from annual crop, non-irrigated, intensive Transformation, to annual crop, non-irrigated, intensive
12815 Transformation, from permanent crop, irrigated, intensive Transformation, to permanent crop, irrigated, intensive
12831 Transformation, from annual crop, non-irrigated, intensive Transformation, to annual crop, non-irrigated, intensive
12839 Transformation, from annual crop Transformation, to annual crop
4678 Transformation, from unspecified Transformation, to unspecified
4678 Transformation, from industri

13755 Transformation, from annual crop, non-irrigated Transformation, to annual crop, non-irrigated
5563 Transformation, from permanent crop, irrigated Transformation, to permanent crop, irrigated
5564 Transformation, from industrial area Transformation, to industrial area
5587 Transformation, from permanent crop, irrigated Transformation, to permanent crop, irrigated
13786 Transformation, from arable land, unspecified use Transformation, to arable land, unspecified use
13796 Transformation, from arable land, unspecified use Transformation, to arable land, unspecified use
5606 Transformation, from permanent crop, irrigated Transformation, to permanent crop, irrigated
13813 Transformation, from pasture, man made, intensive Transformation, to pasture, man made, intensive
5636 Transformation, from pasture, man made, intensive Transformation, to pasture, man made, intensive
5666 Transformation, from arable land, unspecified use Transformation, to arable land, unspecified use
5690 Transform

7331 Transformation, from unspecified Transformation, to unspecified
7331 Transformation, from industrial area Transformation, to industrial area
7343 Transformation, from pasture, man made, intensive Transformation, to pasture, man made, intensive
7343 Transformation, from pasture, man made, extensive Transformation, to pasture, man made, extensive
7374 Transformation, from forest, intensive Transformation, to forest, intensive
7378 Transformation, from unspecified Transformation, to unspecified
7378 Transformation, from industrial area Transformation, to industrial area
7396 Transformation, from permanent crop, irrigated Transformation, to permanent crop, irrigated
7400 Transformation, from annual crop, non-irrigated, intensive Transformation, to annual crop, non-irrigated, intensive
7405 Transformation, from industrial area Transformation, to industrial area
7421 Transformation, from permanent crop, irrigated Transformation, to permanent crop, irrigated
7467 Transformation, from pas

In [100]:
ratio_rv_dict_per_activity

{2: {1655: {635: {'loc': 0.0, 'scale': 1e-17}}},
 31: {1655: {635: {'loc': 4.5886412, 'scale': 1e-17}}},
 32: {1655: {635: {'loc': 4.5886412, 'scale': 1e-17}}},
 41: {1655: {1338: {'loc': 0.0, 'scale': 0.48501355369637095}}},
 45: {1655: {635: {'loc': 0.0, 'scale': 5.5091735160646577e-05}}},
 55: {1655: {635: {'loc': 4.6051702, 'scale': 1e-17}}},
 59: {1655: {635: {'loc': 0.0, 'scale': 0.00010805032449841224}}},
 60: {1655: {635: {'loc': 3.174715, 'scale': 0.00011892358995696764}}},
 69: {1655: {635: {'loc': 4.6051702, 'scale': 0.17642158052117829}}},
 72: {78: {468: {'loc': 0.0, 'scale': 5.9852932333745914e-05}}},
 76: {1351: {635: {'loc': 0.19782639, 'scale': 8.5449032485282071e-05}}},
 104: {1351: {468: {'loc': 0.0, 'scale': 0.30542147378812817}}},
 107: {22: {1032: {'loc': 0.0, 'scale': 1e-17}}},
 134: {1655: {635: {'loc': 0.0, 'scale': 0.00011423815239643584}}},
 150: {1655: {635: {'loc': 0.0, 'scale': 1.067988297751739e-05}}},
 153: {1351: {635: {'loc': 0.0, 'scale': 1e-17}}},
 1

In [108]:
len(correlated_bio_params[np.where(correlated_bio_params['uncertainty_type'] == 1)])

1342

In [106]:
len(correlated_bio_params)

353369

In [6]:
biosphere_matrix=LCA_obj.biosphere_matrix

In [14]:
biosphere_matrix[1959,1]

0.0

In [9]:
biosphere_matrix.shape

(1960, 13831)